Repository wecode-bootcamp-korea/26-2nd-WeAreBnB-frontend, pull requests merged in 2021-11, with the labels that each got.

#8 [26기 김여름] Modified: 파일구조 수정
  src/pages/RoomLists/RoomBox/RoomBox.js
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/FilterButton.js
  src/pages/RoomLists/components/Map.js
  src/pages/RoomLists/components/RoomBox.js
  src/pages/RoomLists/components/RoomPhotos.js
Labels: Status: 리뷰 요청

#9 [26기 김여름] Add: image slide 기능 추가
  public/data/Rooms.json
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/RoomBox.js
  src/pages/RoomLists/components/RoomPhotos.js
Labels: Status: 리뷰 요청

#2 [26기 박소윤]Add : 로그인페이지 리팩토링
  .gitignore
  src/Router.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/components/LoginKakao.js
  src/pages/Login/components/Oauth.js
  src/pages/Login/components/Redirect.js
Labels: Status: 리뷰 요청

#6 [26기 김여름] google map API 적용
  .env
  .gitignore
  package-lock.json
  package.json
  public/data/Locations.json
  public/data/RoomData.json
  public/images/17560_12351_5947.jpeg
  src/pages/RoomLists/components/Map.js
Labels: Status: 리뷰 요청

#14 [26기 석예주]Modify: router.js detail path 수정
  src/Router.js
Labels: Status: Rebase 요청

#11 [26기 김여름] Add: Filter 기능 추가
  package-lock.json
  package.json
  public/data/Rooms.json
  public/data/SUBFILTER.json
  src/Router.js
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/FilterButton.js
  src/pages/RoomLists/components/PriceFilter.js
  src/pages/RoomLists/components/RoomTypeFilter.js
  src/pages/RoomLists/components/data.js
  src/styles/Mixin.js
Labels: Status: 리뷰 요청

#15 [26기 김여름]modify: airbnb library initialize
  src/index.js
  src/pages/RoomLists/components/PriceFilter.js
  src/pages/RoomLists/components/RoomPhotos.js
Labels: Status: 리뷰 요청

#12 [26기 김여름] Add: pagination 기능 추가
  public/data/Rooms.json
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/RoomBox.js
Labels: Status: 리뷰 요청

#3 [26기 박소윤]Modify: 리뷰기능 수정. 예약 리스트 슬라이드 추가
  .env
  .gitignore
  public/data/Mypage/Profile.json
  public/data/Mypage/Review.json
  public/data/Mypage/RoomLists.json
  src/pages/Login/components/Oauth.js
  src/pages/Login/components/Redirect.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/components/CommentList.js
  src/pages/MyPage/components/MyLogDetail.js
  src/pages/MyPage/components/MyProfile.js
  src/pages/MyPage/components/MyReservation.js
  src/pages/MyPage/components/MyReview.js
Labels: Status: 도움 요청, Status: 리뷰 요청

#16 [26기 김여름] Modify/filter filter 기능 일부 수정
  src/index.js
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/RoomBox.js
  src/pages/RoomLists/components/RoomPhotos.js
Labels: Status: 리뷰 요청

#17 [26기 김여름] Add: marker 추가
  .gitignore
  public/data/Locations.json
  public/data/RoomData.json
  public/data/Rooms.json
  public/images/Rectangle 1.png
  public/images/marker_black.png
  public/images/marker_white.png
  src/index.js
  src/pages/RoomLists/Marker.js
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/Map.js
  src/pages/RoomLists/components/RoomBox.js
Labels: Status: 리뷰 요청

#10 [26기 임기범] Add: Nav 레이아웃 완료
  public/data/PersonData.json
  src/components/Nav/ActivatedNav.js
  src/components/Nav/LoginPop.js
  src/components/Nav/Nav.js
  src/components/Nav/Person.js
  src/pages/Main/Component/City.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#5 [26기 석예주] Add: 상세페이지 데이터 형식 변경 / POST 수정
  package-lock.json
  package.json
  public/data/detailData.json
  src/index.js
  src/pages/Detail/Detail.js
  src/pages/Detail/components/DetailCheck.js
  src/pages/Detail/components/DetailConvenience.js
  src/pages/Detail/components/DetailData.js
  src/pages/Detail/components/DetailDesc.js
  src/pages/Detail/components/DetailHostTitle.js
  src/pages/Detail/components/DetailImages.js
  src/pages/Detail/components/DetailPointDesc.js
  src/pages/Detail/components/DetailReview.js
  src/pages/Detail/components/DetailTitle.js
  src/pages/Detail/components/ReservationDate.js
  src/pages/Detail/components/ReservationPerson.js
  src/pages/Detail/components/ReservationSider.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#18 [26기 박소윤] modify flow
  .env
  src/components/Nav/ActivatedNav.js
  src/components/Nav/LoginPop.js
  src/components/Nav/Nav.js
  src/components/Nav/Person.js
  src/config.js
  src/index.js
  src/pages/Detail/Detail.js
  src/pages/Detail/components/ReservationSider.js
  src/pages/Login/Login.js
  src/pages/Login/components/Redirect.js
  src/pages/Main/Main.js
  src/pages/MyPage/components/MyProfile.js
  src/pages/RoomLists/RoomLists.js
  src/pages/RoomLists/components/Map.js
  src/pages/RoomLists/components/RoomBox.js
  src/styles/theme.js
Labels: Status: 리뷰 요청
